'use strict';
// Local JavaScript/minimal DOM execution. This is not a browser visual check.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const dir=path.resolve(process.argv[2]),audit=JSON.parse(fs.readFileSync(path.join(dir,'chart_audit.json'),'utf8'));
const hash=v=>crypto.createHash('sha256').update(v).digest('hex');let filters=0,selections=0,charts=0,draws=0;const checks=[];
function boot(relative,fragment=''){
 const html=fs.readFileSync(path.join(dir,relative),'utf8');assert.equal(hash(html),audit.outputs[relative]);
 const payload=html.match(/<script type="application\/json" id="frozen-data">([\s\S]*?)<\/script>/)[1],data=JSON.parse(payload),script=html.match(/<script>\s*([\s\S]*?)<\/script>/)[1];
 assert(!/\b(fetch|XMLHttpRequest|WebSocket|EventSource)\b/.test(script));
 const ctx=new Proxy({measureText:t=>({width:String(t).length*6})},{get:(t,k)=>k in t?t[k]:(...args)=>{if(['moveTo','lineTo','fillRect','rect','arc','clearRect','setTransform'].includes(k))assert(args.every(Number.isFinite),`finite ${relative}/${k}: ${args}`);draws++},set:(t,k,v)=>{t[k]=v;return true}}),nodes={};
 class N{constructor(id){this.id=id;this.handlers={};this.dataset={};this.style={};this.options=[];this.value='';this.textContent='';this.disabled=false;this.hidden=false;this.classes=new Set();this.classList={add:n=>this.classes.add(n),remove:n=>this.classes.delete(n),toggle:(n,v)=>v?this.classes.add(n):this.classes.delete(n)}}
 addEventListener(k,f){(this.handlers[k]??=[]).push(f)}fire(k,args={}){const e={target:this,button:0,pointerId:1,clientX:600,clientY:200,preventDefault(){this.prevented=true},...args};for(const f of this.handlers[k]??[])f(e);return e}
 set innerHTML(v){this._html=v;this.options=[...v.matchAll(/<option value="([^"]*)"/g)].map(m=>({value:m[1]}));if(!this.value&&this.options.length)this.value=this.options[0].value;if(this.id==='tradeRows')this.rows=[...v.matchAll(/<tr data-trade="(\d+)">/g)].map(m=>{const n=new N('trade'+m[1]);n.dataset.trade=m[1];n.closest=()=>n;return n})}get innerHTML(){return this._html??''}add(o){this.options.push(o)}setAttribute(k,v){this[k]=v}
 getBoundingClientRect(){return{left:0,top:0,width:1200,height:({price:440,progress:105,rsi:95,equity:122,charts:762}[this.id]??100)}}getContext(){return ctx}setPointerCapture(){}releasePointerCapture(){}scrollIntoView(){}get offsetWidth(){return 300}get offsetHeight(){return 150}
 querySelectorAll(s){if(s==='tr[data-trade]')return nodes.tradeRows.rows??[];if(s==='button[data-tab]')return tabButtons;throw Error(s)} }
 for(const m of html.matchAll(/\bid="([^"]+)"/g))nodes[m[1]]=new N(m[1]);const tabButtons=[...html.matchAll(/<button data-tab="([^"]+)"/g)].map(m=>{const n=new N(m[1]);n.dataset.tab=m[1];n.closest=()=>n;return n});
 for(const m of html.matchAll(/<select id="([^"]+)"[^>]*>([\s\S]*?)<\/select>/g))nodes[m[1]].innerHTML=m[2];nodes['frozen-data'].textContent=payload;
 const handlers={},location={hash:fragment},context={document:{getElementById:id=>{assert(nodes[id],id);return nodes[id]},title:''},location,window:{devicePixelRatio:1,addEventListener:(k,f)=>(handlers[k]??=[]).push(f)},ResizeObserver:class{constructor(fn){this.fn=fn}observe(){this.fn()}},Option:class{constructor(text,value){this.text=text;this.value=value}}};
 vm.createContext(context);vm.runInContext(script,context,{timeout:30000});return{html,data,nodes,context,handlers,location,probe:context.__stateIndex??context.__stateChart??context.__accelerationPage};
}
function check(name,fn){fn();checks.push({name,status:'PASS'})}
const main=boot('index.html'),n=main.nodes,D=main.data;
check('Default account cohort and all four cases',()=>{assert.equal(n.coinCohort.value,'main_full');assert.equal(n.coinCase.value,'V3');assert.equal(main.probe.state().coins.length,346);assert.equal(n.coinCase.options.length,4);assert.equal(D.diagnostics.length,audit.diagnostic_trade_count)});
check('Every tab is operable',()=>{for(const tab of ['accounts','diagnostics','fixed','history']){main.probe.showTab(tab);assert.equal(n[tab].hidden,false);assert.equal(main.probe.state().currentTab,tab)}});
check('Account search/cohort/case/quality/sorting',()=>{for(const cohort of ['main_full','partial','short','excluded','all'])for(const c of ['V3','S1_DEFENSE','S2_TREND','S3_EXTENSION'])for(const qual of ['all','positive','loss','risk','stress','bankrupt','zero']){n.coinCohort.value=cohort;n.coinCase.value=c;n.coinQuality.value=qual;n.coinQuality.fire('change');const expected=D.coins.filter(r=>cohort==='all'||r.cohort===cohort).filter(r=>{const a=r.cases[c];return qual==='all'||a&&(qual==='positive'?a.return_pct>0:qual==='loss'?a.return_pct<=0:qual==='risk'?a.risk_pass:qual==='stress'?a.stress_pass:qual==='bankrupt'?a.bankrupt:a.trades===0)});assert.equal(main.probe.state().coins.length,expected.length);filters++}n.coinQuality.value='all';n.coinCohort.value='all';for(const sort of ['return_pct','max_drawdown_pct','payoff_ratio','win_rate_pct','expectancy_cash','trades','symbol']){n.coinSort.value=sort;n.coinSort.fire('change');const rows=main.probe.state().coins.map(s=>D.coins.find(r=>r.slug===s)),o={main_full:0,partial:1,short:2,excluded:3};assert.equal(rows.length,652);for(let i=1;i<rows.length;i++)assert(o[rows[i].cohort]>=o[rows[i-1].cohort]);filters++}n.coinSearch.value='HYPE';n.coinSearch.fire('input');assert.equal(main.probe.state().coins.length,D.coins.filter(r=>r.symbol.includes('HYPE')).length);n.coinSearch.value='<script>';n.coinSearch.fire('input');assert.equal(main.probe.state().coins.length,0);n.coinReset.fire('click');assert.equal(main.probe.state().coins.length,346);});
check('Every account detail opens with four cases',()=>{for(const coin of D.coins.filter(r=>r.page)){main.probe.coinDetail(coin.slug);assert(n.coinDetail.innerHTML.includes(coin.symbol));assert(n.coinDetail.innerHTML.includes('S3'));selections++}});
check('Diagnostic winner/loss/terminal/side/cohort filters and pagination',()=>{for(const co of ['main_full','partial','short','all'])for(const out of ['all','win','loss','flat'])for(const ex of ['all','nonterminal','sample_end'])for(const side of ['all','1','-1']){n.diagCohort.value=co;n.diagOutcome.value=out;n.diagExit.value=ex;n.diagSide.value=side;n.diagSide.fire('change');const expected=D.diagnostics.filter(t=>(co==='all'||t.cohort===co)&&(out==='all'||out===t.net_outcome)&&(ex==='all'||(ex==='sample_end')===t.terminal_exit)&&(side==='all'||t.side===Number(side)));assert.equal(main.probe.state().trades.length,expected.length);assert.equal((n.diagRows.innerHTML.match(/<tr>/g)||[]).length,Math.min(100,expected.length));filters++}n.diagCohort.value='all';n.diagOutcome.value='all';n.diagExit.value='all';n.diagSide.value='all';n.diagSide.fire('change');n.diagNext.fire('click');assert.equal(main.probe.state().diagPage,1);n.diagPrev.fire('click');assert.equal(main.probe.state().diagPage,0);});
check('Fixed pre-cross bins and surviving-day/MFE conditions',()=>{for(const feature of ['pre_displacement20_bin','pre_efficiency20_bin','pre_volatility_ratio_bin']){n.diagFeature.value=feature;n.diagFeature.fire('change');for(const opt of n.diagBin.options){n.diagBin.value=opt.value;n.diagBin.fire('change');const expected=D.diagnostics.filter(t=>opt.value==='all'||t[feature]===opt.value);assert.equal(main.probe.state().trades.length,expected.length);filters++}}n.diagFeature.value='all';n.diagFeature.fire('change');for(const state of ['first','early1','third','early3','mfe1','below1','mfe2','uncertain']){n.diagState.value=state;n.diagState.fire('change');assert(main.probe.state().trades.length<=D.diagnostics.length);filters++}n.diagState.value='all';n.diagState.fire('change');n.diagSearch.value='HYPE';n.diagSearch.fire('input');assert.equal(main.probe.state().trades.length,D.diagnostics.filter(t=>t.symbol.includes('HYPE')).length);});
check('Fixed-entry controls preserve all three candidates',()=>{for(const co of ['main_full','partial','short'])for(const side of ['all','long','short'])for(const term of ['all','neither_terminal','either_terminal'])for(const control of ['all','baseline_win','baseline_loss','baseline_top5_winner']){n.fixedCohort.value=co;n.fixedSide.value=side;n.fixedTerminal.value=term;n.fixedGroup.value=control;n.fixedGroup.fire('change');assert.equal((n.fixedRows.innerHTML.match(/<tr>/g)||[]).length,3);filters++}});
check('Historical fixed windows, complete/partial denominators and search',()=>{for(const source of ['all',...D.historySources])for(const block of ['full',...D.historyBlockNames])for(const status of ['COMPLETE','PARTIAL','all']){n.historySource.value=source;n.historyBlock.value=block;n.historyStatus.value=status;n.historyStatus.fire('change');const expected=D.history.filter(r=>(source==='all'||r.source_group===source)&&r.block===block&&(block==='full'||status==='all'||r.status===status));assert.equal(main.probe.state().history.length,expected.length);filters++}n.historySearch.value='BTC';n.historySearch.fire('input');assert(main.probe.state().history.every(k=>D.history.find(r=>r.source_group+'/'+r.run_key+'/'+r.block===k).symbol.includes('BTC')))});
check('Historical scope retains all 680 codes including four with no trading window',()=>{n.historySearch.value='';n.historySource.value='all';n.historySource.fire('change');assert.equal(D.historyScope.length,680);assert.equal((n.historyScopeRows.innerHTML.match(/<tr>/g)||[]).length,680);assert.equal(D.historyScope.filter(r=>r.segments_with_trading_window===0).length,4);});
const accel=boot('acceleration.html');
check('Acceleration table defaults and all cohort/side/horizon/factor controls',()=>{assert.equal(accel.probe.state().cohort,'main_full');assert.equal(accel.probe.state().side,-1);assert.equal(accel.probe.state().horizon,10);assert.equal(accel.nodes.accFactor.options.length,8);for(const co of ['main_full','partial','short'])for(const side of [-1,1])for(const days of [5,10,20])for(const factor of ['all',...Object.keys(accel.data.labels)]){accel.nodes.accCohort.value=co;accel.nodes.accSide.value=String(side);accel.nodes.accHorizon.value=String(days);accel.nodes.accFactor.value=factor;accel.nodes.accFactor.fire('change');const expected=accel.data.factors.filter(r=>r.cohort===co&&r.side===side&&r.horizon_days===days&&(factor==='all'||r.factor===factor));assert.equal(accel.probe.state().visibleFactors.length,expected.length);assert.equal((accel.nodes.accRows.innerHTML.match(/<tr>/g)||[]).length,expected.length);assert.equal((accel.nodes.coverageRows.innerHTML.match(/<tr>/g)||[]).length,18);assert.equal((accel.nodes.earlyRows.innerHTML.match(/<tr>/g)||[]).length,3);filters++;}for(const r of accel.data.links)assert(fs.existsSync(path.resolve(dir,r.href)),r.href);});
for(const [relative,p] of Object.entries(audit.pages)){
 const page=boot(relative),a=page.data;assert.equal(page.probe.state().armKey,'V3');assert.equal(a.fee,.001);assert.equal(a.slip,.0004);assert.equal(Object.keys(a.arms).length,4);
 if(p.dataset!=='current')assert(page.html.includes('不能认定完整周期验证通过'));
 for(const [caseId,arm] of Object.entries(a.arms)){
  page.nodes.armSelect.value=caseId;page.nodes.armSelect.fire('change');assert.equal(page.probe.state().armKey,caseId);assert.equal(page.nodes.tradeSelect.options.length,arm.trades.length+1);assert.equal((page.nodes.tradeRows.rows||[]).length,arm.trades.length);assert.equal(arm.trades.length,p.cases[caseId].trades);assert.equal(arm.trades.reduce((s,t)=>s+t.progress.length,0),p.cases[caseId].stop_rows);
  const selected=a.symbol.includes('HYPE')?arm.trades:arm.trades.length?[arm.trades[0],arm.trades.at(-1)]:[];
  for(const t of selected){page.nodes.tradeSelect.value=String(t.id);page.nodes.tradeSelect.fire('change');assert.equal(page.probe.state().selected,t.id);assert.equal((page.nodes.auditRows.innerHTML.match(/<tr>/g)||[]).length,t.progress.length);if(t.diagnostic)assert.equal(page.nodes.diagnosticDetail.hidden,false);selections++}
 }
 if(charts===0){page.nodes.full.fire('click');let width=page.probe.state().right-page.probe.state().left;page.nodes.price.fire('keydown',{key:'+'});assert(page.probe.state().right-page.probe.state().left<width);page.nodes.price.fire('wheel',{deltaY:-100});page.nodes.price.fire('pointerdown',{clientX:600});page.nodes.price.fire('pointermove',{clientX:700});page.nodes.price.fire('pointerup',{clientX:700});page.nodes.price.fire('pointermove',{clientX:650,clientY:200});assert.equal(page.nodes.tooltip.hidden,false);page.nodes.price.fire('dblclick');page.nodes.recent.fire('click');assert(page.probe.state().right-page.probe.state().left<=120*86400000)}
 charts++;if(charts%100===0)process.stdout.write(`Validated ${charts} chart pages\n`);
}
check('All generated chart pages were executed',()=>assert.equal(charts,audit.total_chart_pages));
check('All static local links and generated data links resolve',()=>{const links=[...D.links,...D.diagLinks,...D.fixedLinks,...D.historyLinks].map(r=>r.href).concat(D.coins.filter(r=>r.page).map(r=>r.page),D.history.map(r=>r.page));for(const href of links)assert(fs.existsSync(path.resolve(dir,decodeURIComponent(href.split('#')[0]))),href);for(const [name]of Object.entries(audit.pages)){const html=fs.readFileSync(path.join(dir,name),'utf8');for(const m of html.matchAll(/href="([^"#][^"]*)"/g)){if(m[1].includes('${'))continue;assert(fs.existsSync(path.resolve(path.dirname(path.join(dir,name)),decodeURIComponent(m[1].split('#')[0]))),name+' '+m[1]);}}});
const result={status:'PASS',scope:'Generated JavaScript run under local minimal DOM/canvas; no browser or visual claim',network_used:false,browser_used:false,checks,filters,detail_and_trade_selections:selections,chart_pages_executed:charts,canvas_draw_calls:draws,html_index_sha256:hash(fs.readFileSync(path.join(dir,'index.html'))),chart_audit_sha256:hash(fs.readFileSync(path.join(dir,'chart_audit.json'))),probe_sha256:hash(fs.readFileSync(__filename)),node_version:process.version};fs.writeFileSync(path.join(dir,'offline_interaction_qa.json'),JSON.stringify(result,null,2)+'\n');process.stdout.write(JSON.stringify(result)+'\n');
