#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""One-time C0/C1 preparation. Never computes portfolio returns."""
import ast,csv,datetime,gzip,hashlib,importlib.metadata as md,json,pathlib,platform,shutil
import ta
ROOT=pathlib.Path(__file__).resolve().parents[1]
WORK=ROOT.parents[2]/'work-M0275'
OLD=ROOT.parents[2].parent/'dot-public-strategies-20261003'
def sha(p):return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def write(p,x):
    with p.open('x') as f:json.dump(x,f,indent=2,ensure_ascii=False);f.write('\n')
def utc():return datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z')
assert shutil.disk_usage(ROOT).free>=5*1024**3
source=WORK/'sources/Heracles.py';assert source.stat().st_size==3867 and sha(source)=='5b25d85297329243d7a3c65770975b5a70e52ec2684b1e007e5d8a3d1a7e3718'
master=pathlib.Path('/workspace/scratch/eedf5ebf8fc6/grok-handoff-work/delivery/quant-master-draft.csv')
row=next(r for r in csv.reader(master.open()) if r[0]=='M0275')
assert row[1]=='Heracles' and 'shift 15/9' in row[3]
html=WORK/'sources/binance-age.html';raw=html.read_bytes();decoded=gzip.decompress(raw) if raw[:2]==b'\x1f\x8b' else raw;txt=decoded.decode();assert 'BTC/USDT' in txt and '2022-07-08 14:00' in txt
age={'id':'M0275','status':'HISTORICAL_EXISTENCE_SUPPORTED_AGE_ELIGIBILITY_ASSUMED','source_url':'https://www.binance.com/en/support/announcement/detail/10435147c55d4a40b64fcbf43cb46329','publication_utc':'2022-07-06T14:00:00Z','historical_availability_not_later_than_utc':'2022-07-08T14:00:00Z','page_fetched_at_utc':utc(),'page_bytes':html.stat().st_size,'page_sha256':sha(html),'response_content_encoding':'gzip' if raw[:2]==b'\x1f\x8b' else 'identity','decoded_html_sha256':hashlib.sha256(decoded).hexdigest(),'bounded_quote':'zero-fee trading for BTC spot trading pairs at 2022-07-08 14:00 (UTC).','fact_paraphrase_zh':'公告名单明确包括BTC/USDT，足以支持该交易对在2022年7月已存在的历史事实；不是使用今天的上市名单。','earliest_possible_strategy_order_utc':'2023-01-01T04:00:00Z','age_lower_bound_days':(datetime.datetime(2023,1,1,4,tzinfo=datetime.timezone.utc)-datetime.datetime(2022,7,8,14,tzinfo=datetime.timezone.utc)).total_seconds()/86400,'min_days_listed':100,'assumption':'BTC/USDT在历史存在证据与整个评价窗口之间未发生重上市重置；未逐日复刻AgeFilter所用的最近100根1d candle count。','framework_reference':'Freqtrade 2025.9 c66e221012cd4d68cfdacf4735b38af33a487961 AgeFilter supports_backtesting=NO','strict_agefilter_replication':False,'pit_universe_proven':False}
write(ROOT/'specs/agefilter-evidence.json',age)
fetch=json.loads((WORK/'sources/fetch-receipt.json').read_text())
manifest={'strategy_source':{'url':'https://raw.githubusercontent.com/freqtrade/freqtrade-strategies/f3340ce11f5bdf62f598522e64d1f5638eaa13f5/user_data/strategies/Heracles.py','repository_commit':'f3340ce11f5bdf62f598522e64d1f5638eaa13f5','filename':'Heracles.py','bytes':source.stat().st_size,'sha256':sha(source),'author':'Mablue / Masoud Azizi','license':'GPL-3.0','upstream_historical_runtime':'UNKNOWN'},'private_master_provenance':{'id':'M0275','master_sha256':sha(master),'selected_row_sha256':hashlib.sha256(json.dumps(row,ensure_ascii=False).encode()).hexdigest(),'full_row_published':False},'reference_only_sources':fetch,'license_reference':{'url':'https://raw.githubusercontent.com/freqtrade/freqtrade-strategies/f3340ce11f5bdf62f598522e64d1f5638eaa13f5/LICENSE','sha256':'8ceb4b9ee5adedde47b31e975c1d90c73ad27b6b165a1dcd80c7c545eb65b903'},'full_third_party_source_in_publication':False}
write(ROOT/'specs/source-manifest.json',manifest)
# Verify light manifest source objects on both independently fetched snapshots.
light=json.loads((ROOT/'specs/input-manifest-inherited.json').read_text());comparisons={}
for name in ['dot-b001-primary-v1','dot-b001-rebuild-v1']:
    base=OLD/f'data/raw/ohlcv/exchange=binance/market_type=spot/timeframe=4h/source=binance_vision/snapshot={name}'
    actual=json.loads((base/'manifest.json').read_text())
    assert actual['timeframe']==light['timeframe'] and actual['schema']==light['schema']
    for a,b in zip(actual['archives'],light['archives']):
        for kind in ['zip','checksum','csv']:
            assert a[kind]['bytes']==b[kind]['bytes'] and a[kind]['sha256']==b[kind]['sha256']
    assert len(actual['archives'])==len(light['archives'])==25
    assert actual['canonical_csv']['sha256']==light['canonical_csv']['sha256']
    comparisons[name]={'archive_triplets':25,'source_objects':75,'match':'bytes/sha256/schema/timeframe/canonical','manifest_sha256':sha(base/'manifest.json')}
write(ROOT/'artifacts/C0-source-input-qa.json',{'id':'M0275','completed_at_utc':utc(),'checkpoint':'C0','status':'PASS_FOR_DIAGNOSTIC_ONLY','strategy_returns_read':False,'source_matches_claim':True,'original_id_matches_master':True,'input_snapshots':comparisons,'input_rows':4572,'evaluation_rows':4386,'quality_status':'DIAGNOSTIC_ONLY','trusted':False,'strict_core_finality':'NOT_ESTABLISHED_HTTP451_provider_clock_current_bucket','remaining_disk_bytes':shutil.disk_usage(ROOT).free,'age_filter':'historical lower-bound proxy only','one_minute_evidence_accessed':False})
packages={k:md.version(k) for k in ['numpy','pandas','ta']}
ta_files={k:sha(pathlib.Path(ta.__file__).parent/k) for k in ['__init__.py','utils.py','volatility.py']}
write(ROOT/'specs/requirements.lock.txt.json',{'python':platform.python_version(),'packages':packages,'ta_file_hashes':ta_files,'cpu_threads':1,'process_memory_limit_bytes':1536*1024**2})
exposure={'id':'M0275','recorded_before_results_utc':utc(),'evaluation':['2023-01-01T00:00:00Z','2025-01-01T00:00:00Z'],'window_previously_exposed':True,'prior_known_usage':['M0256 BTCUSDT 4h, same evaluation window'],'historical_total_search_count':'UNKNOWN','current_strategy_ids':1,'strategy_configurations':4,'controls':1,'parameter_searches':0,'oos_claim':False,'DSR_PBO_claim':False,'window_or_parameter_change_after_results_forbidden':True}
write(ROOT/'specs/exposure.json',exposure)
spec={'id':'M0275','name':'Heracles / BTCUSDT spot 4h','run_id':'M0275-20261003-first-replay','variant_id':'M0275-BTCUSDT-4H-HERACLES-15-9-20261003','family':'PUBLIC-M0275-HERACLES','fidelity_class':'HYPOTHESIS','data_quality_status':'DIAGNOSTIC_ONLY','strict_reproductions':0,'frozen_at_utc':utc(),'returns_computed_before_freeze':False,
'parameters':{'donchian_window':10,'donchian_offset':0,'keltner_window':20,'keltner_window_atr':10,'keltner_original_version':True,'fillna':False,'buy_indicator_shift':15,'buy_crossed_indicator_shift':9,'buy_div_min':.16,'buy_div_max':.75,'parameter_load':'explicit source buy_params overrides IntParameter default16; no external parameter JSON/config override; no hyperopt'},
'signal':{'entry':'0.16 <= Donchian_pband[t-15] / Keltner_wband[t-9] <= 0.75, inclusive','exit':'always 0; no indicator exit','no_volume_guard':'no additional strategy volume predicate; input QA independently requires positive activity','nan_policy':'ta.dropna on date/OHLCV only; actual 0 rows removed; any real deletion is blocker. Indicator NaN retained and yields false entry. No bfill/ffill.','indicator_units':'DCP dimensionless [0,1]; original-version KCW is percentage width*100, not ATR modern Keltner','availability':'completed native 4h candles only'},
'risk':{'minimal_roi':{'0':.598,'644':.166,'3269':.115,'7289':0},'stoploss':-.256,'trailing':False,'roi_clock':'integer floor wall-clock minutes from effective entry open (14:00 for outage bucket) to effective current bar open; original minute keys retained','roi_inside_bar_policy':'select ROI tier at effective observable open and hold it for entire bar; if next minute boundary is inside interval before next observable open, defer new tier until that open if still held; never use whole-bar high for a tier unavailable at bar open. This can understate or otherwise alter exits vs minute replay, and is not exact Freqtrade runtime replication.','roi_threshold_formula':'entry_fill*(1+entry_fee)*(1+ROI)/(1-exit_fee)','roi_execution_slippage':'sell reference at target or favorable raw opening gap, then 2bps adverse slip; zero ROI can realize a small net loss','stop_threshold_formula':'entry_fill*(1-0.256), sell costs added; gap-through executes at worse observed open','samebar_priority':['if flat: due entry at effective open','for existing/new position: open<=stop -> stop gap; else open>=current ROI target -> ROI gap','otherwise low<=stop first; else high>=current ROI target -> ROI','ROI tier transition inside observation interval cannot act within that interval','no reentry after exit during same bar'],'boundary_logging':'candidate transition while position exists at opening; does not assert still held at later boundary; next observation honors 14:00 outage resume'},
'execution':{'initial_cash':100000,'cash_currency':'USDT','cash_budget_fraction':.95,'budget_includes_fee':True,'slippage_bps':2,'long_only':True,'leverage':1,'max_positions':1,'pyramiding':False,'cash_interest':0,'funding':'not applicable spot no borrowing','fill':'full fractional fills; next 4h observed open, market proxy plus adverse slippage','known_halt':'2023-03-24 11:27–14:00 UTC; 12:00 native bar uses 14:00 1h resumption-open proxy. 08:00 intrabar interval ends11:26:59.999; 12:00 interval starts14:00. No tick precision.','terminal':'no forced liquidation; holdings marked to final raw close, hypothetical closing fee not charged','missing_microstructure':'historical lot size, min notional, queue, partial fills, liquidity and all-history downtime unproven'},
'age_filter':{'min_days_listed':100,'proxy':'historical exchange announcement confirms >176 elapsed days by first possible strategy order, continuous listing assumed; not original recent100 daily candle count','source_evidence':'specs/agefilter-evidence.json','universe':'fixed predeclared single BTCUSDT; not author pairlist or point-in-time universe'},
'input':{'sha256':'9f5cb39c1426ec91098bb8a1b1f0c926b80760e66fe452d6b0c0aa55429d126c','bytes':1298564,'rows':4572,'timeframe':'4h','source':'Binance Vision native monthly 4h archives','exchange':'binance','market_type':'spot','symbol':'BTCUSDT','start':'2022-12-01T00:00:00Z','end_exclusive':'2025-01-01T00:00:00Z','dataset_id':'binance.spot.BTCUSDT.4h.native12.dot-b001-primary-v1','scope':'EXPLICIT_DIAGNOSTIC','registered_status':'UNACCEPTED','trusted':False,'reason_not_trusted_loader':'explicit spot task does not use perpetual V3 bundle; equivalent row/integrity QA but strict core finality not established, no TRUSTED or promotion claim'},
'evaluation':{'start':'2023-01-01T00:00:00Z','end_exclusive':'2025-01-01T00:00:00Z','rows':4386,'initial_state':'all cash; warmup indicators only, no warmup pending signal. First possible strategy entry2023-01-01 04:00UTC'},
'cases':[{'name':'base','fee_bps':8,'delay_bars':1},{'name':'fee0','fee_bps':0,'delay_bars':1},{'name':'fee20','fee_bps':20,'delay_bars':1},{'name':'delay2','fee_bps':8,'delay_bars':2},{'name':'buyhold','fee_bps':8,'delay_bars':1,'buy_hold':True}],
'benchmark':'same BTCUSDT at first evaluation open,95% inclusive cash budget,same8bps fee and2bps slip,no risk exits,no terminal forced sale',
'metrics':{'total_return':'final marked equity /100000-1','annualized_return':'(final/initial)^(365/731)-1','max_drawdown':'all unsampled4h close equities including initial capital, not intrabar','sharpe_daily':'UTC end-of-day returns including initial equity, sample std ddof1,sqrt365,rf0','sharpe_4h':'4h close returns sqrt2190,ddof1','exposure':'bar-close position fraction, not exact elapsed time'},
'dependencies':{'python':platform.python_version(),'packages':packages,'ta_file_hashes':ta_files,'original_runtime':'unknown; ta0.11.0 pinned for this instance'},
'frozen_file_hashes':{str(p.relative_to(ROOT)):sha(p) for folder in ['scripts','specs','artifacts'] for p in sorted((ROOT/folder).glob('*')) if p.is_file() and p.name!='protocol.json'}}
write(ROOT/'specs/protocol.json',spec)
write(ROOT/'artifacts/C1-freeze-receipt.json',{'checkpoint':'C1','frozen_at_utc':utc(),'protocol_sha256':sha(ROOT/'specs/protocol.json'),'files':spec['frozen_file_hashes'],'returns_computed':False,'source_returns_in_comments_ignored':True,'remaining_disk_bytes':shutil.disk_usage(ROOT).free})
print(json.dumps({'C0':'PASS_FOR_DIAGNOSTIC_ONLY','C1':'FROZEN_NO_RETURNS','protocol_sha256':sha(ROOT/'specs/protocol.json'),'at_utc':utc()},indent=2))
