#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""C1 freeze only; refuses overwrite and computes no returns."""
import argparse,datetime,hashlib,importlib.metadata as md,json,pathlib,platform
import talib
ROOT=pathlib.Path(__file__).resolve().parents[1]
def sha(p):return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def write(p,x):
 with pathlib.Path(p).open('x') as f:json.dump(x,f,indent=2,ensure_ascii=False,allow_nan=False);f.write('\n')
def main():
 p=argparse.ArgumentParser();p.add_argument('--sources',required=True);p.add_argument('--handoff',required=True);a=p.parse_args();sources=pathlib.Path(a.sources);handoff=pathlib.Path(a.handoff)
 pre=json.loads((handoff/'M0317-preflight.json').read_text());now=datetime.datetime.now(datetime.timezone.utc).isoformat()
 sm={'id':'M0317','strategy':pre['source'],'framework_commit':'c66e221012cd4d68cfdacf4735b38af33a487961','source_download_started_utc':'2026-10-03T10:53:45Z','verified_at_utc':now,'master_identity':'M0317/mabStra/freqtrade-strategies unchanged; catalog row not published','strategy_commit':'f3340ce11f5bdf62f598522e64d1f5638eaa13f5','assignment_commit':'344e8b361d28004ce36949efe3b3aeda65b5a9f9','files':{}}
 for f in sources.iterdir():
  url=pre['source']['url'] if f.name=='mabStra.py' else ('https://raw.githubusercontent.com/freqtrade/freqtrade-strategies/f3340ce11f5bdf62f598522e64d1f5638eaa13f5/LICENSE' if f.name=='LICENSE' else f'https://raw.githubusercontent.com/freqtrade/freqtrade/{sm["framework_commit"]}/freqtrade/strategy/{f.name.removeprefix("freqtrade-")}')
  sm['files'][f.name]={'sha256':sha(f),'bytes':f.stat().st_size,'url':url,'public_full_copy':False}
 assert sm['files']['mabStra.py']['sha256']==pre['source']['sha256'];write(ROOT/'specs/source-manifest.json',sm)
 dep={'python':platform.python_version(),'packages':{n:md.version(n) for n in ['numpy','pandas','TA-Lib']},'talib_c_version':str(talib.__ta_version__),'talib_file_hashes':{p.name:sha(p) for p in pathlib.Path(talib.__file__).parent.iterdir() if p.is_file() and (p.name in ['__init__.py','abstract.py'] or p.name.endswith('.so'))},'original_author_runtime':'unknown; no full Freqtrade install or execution parity claimed'}
 write(ROOT/'specs/dependencies.json',dep)
 exposure={'id':'M0317','recorded_before_results_utc':now,'evaluation':['2023-01-01T00:00:00Z','2025-01-01T00:00:00Z'],'window_previously_exposed':True,'prior_known_usage':['M0256 BTCUSDT4h','M0275 BTCUSDT4h'],'parallel_window_usage':['M0316'],'historical_total_search_count':'UNKNOWN','current_strategy_ids':1,'strategy_configurations':4,'controls':1,'parameter_searches':0,'oos_claim':False,'DSR_PBO_claim':False,'window_or_parameter_change_after_results_forbidden':True}
 write(ROOT/'specs/exposure.json',exposure)
 spec={'id':'M0317','name':'mabStra / BTCUSDT spot4h source-default diagnostic','run_id':'M0317-20261003-first-replay','variant_id':'M0317-BTCUSDT-4H-MABSTRA-DEFAULT-20261003','family':'PUBLIC-M0317-MABSTRA','fidelity_class':'HYPOTHESIS','data_quality_status':'DIAGNOSTIC_ONLY','strict_reproductions':0,'frozen_at_utc':now,'returns_computed_before_freeze':False,
 'parameters':pre['exact_rules']['effective_parameter_values'],
 'signal':{'entry':'SMA7/SMA14 and SMA14/SMA28 both strictly >0.295 and <2.2545','exit':'SMA14/SMA7 and SMA28/SMA14 both strictly >2.8144 and <1.5459; impossible; preserved without repair','sma':'TA-Lib abstract.SMA uses close; periods7/14/28','nan_policy':'warmup NaN retained; comparisons false; no deletion/fill','no_volume_guard':'source has no volume predicate; data audit requires positive activity','availability':'completed native4h candles only','conflicts':'no entry/exit conflicts possible because sell interval empty','default_loading':'original parameter constructor AST executed; decimal4 rounding, no clamp to0..2; no buy/sell_params dict and no external parameter JSON or hyperopt'},
 'risk':{'minimal_roi':pre['exact_rules']['minimal_roi'],'stoploss':-.128,'trailing':False,'trailing_basis':'source absent; pinned IStrategy class defaultFalse, AST verified','roi_clock':'integer floor wall-clock minutes from effective entry open to effective current bar open; original minute keys retained','roi_inside_bar_policy':'select ROI tier at effective observable open and hold for entire bar; minute boundary strictly inside interval before next effective open is deferred until that open if still held; never use high before tier exists. Diagnostic proxy, not exact Freqtrade runtime','roi_threshold_formula':'entry_fill*(1+entry_fee)*(1+ROI)/(1-exit_fee)','roi_execution_slippage':'sell target or favorable raw open gap then2bps adverse slip; ROI0 may realize small loss','stop_threshold_formula':'entry_fill*(1-0.128), exit costs additional; adverse gap uses raw open','samebar_priority':['if flat due buy at effective open','existing/new position: open<=stop first; else open>=ROI target','otherwise low<=stop before high>=ROI target','no reentry after samebar exit','intra-observation ROI boundary deferred to next effective open'],'boundary_logging':'candidate transition only, does not claim position survives until future boundary'},
 'execution':{'initial_cash':100000,'cash_currency':'USDT','cash_budget_fraction':.95,'budget_includes_fee':True,'slippage_bps':2,'long_only':True,'leverage':1,'max_positions':1,'pyramiding':False,'cash_interest':0,'funding':'not applicable spot without borrowing','fill':'full fractional market-order proxy at next observed4h open plus adverse slippage','order_assumption':'source omits order overrides; pinned IStrategy inherited defaults entry/exit/stoploss=limit and time_in_force=GTC. This diagnostic explicitly overrides to market-proxy fills; NOT native limit-order replication','runtime_assumptions':{'ignore_roi_if_entry_signal':False,'use_exit_signal':True,'exit_profit_only':False,'stoploss_on_exchange':False},'known_halt':'2023-03-24 11:27–14:00UTC; nominal12:00 open uses retained verified14:00 1h open proxy; previous08:00 intrabar end11:26:59.999;12:00 interval starts14:00','terminal':'no forced liquidation; remaining inventory marked at final raw close, no unexecuted sell cost','missing_microstructure':'lot size, min notional, queue, partial fills, liquidity, ticks and all-history downtime unproven'},
 'input':{'sha256':pre['data_reference']['sha256'],'bytes':1298564,'rows':4572,'timeframe':'4h','source':'Binance Vision native monthly4h archives','exchange':'binance','market_type':'spot','symbol':'BTCUSDT','start':'2022-12-01T00:00:00Z','end_exclusive':'2025-01-01T00:00:00Z','dataset_id':'binance.spot.BTCUSDT.4h.native12.dot-b001-primary-v1','scope':'EXPLICIT_DIAGNOSTIC','registered_status':'UNACCEPTED','trusted':False,'reason_not_trusted_loader':'explicit spot assigned diagnostic reuse; perpV3 bundle not applicable; equivalent row/integrity audits run, but strict finality/PIT/tradability unproven; not promotion'},
 'evaluation':{'start':'2023-01-01T00:00:00Z','end_exclusive':'2025-01-01T00:00:00Z','rows':4386,'initial_state':'100% cash;2022-12 indicators only; no pending warmup order; first strategy eligible2023-01-01 04:00UTC'},
 'cases':[{'name':'base','fee_bps':8,'delay_bars':1},{'name':'fee0','fee_bps':0,'delay_bars':1},{'name':'fee20','fee_bps':20,'delay_bars':1},{'name':'delay2','fee_bps':8,'delay_bars':2},{'name':'buyhold','fee_bps':8,'delay_bars':1,'buy_hold':True}],
 'benchmark':'same BTCUSDT first evaluation open;95% inclusive cash budget;8bps fee2bps slip; no risk exits or forced final sale',
 'metrics':{'total_return':'final marked equity/initial-1','annualized_return':'(final/initial)^(365/731)-1','max_drawdown':'all4h close equity plus initial cash; not intrabar','sharpe_daily':'UTC EOD equity returns incl initial capital, sample std ddof1,sqrt365,rf0','sharpe_4h':'4h close returns sqrt2190,ddof1','exposure':'bar-close position fraction; not exact wall-clock exposure'},
 'author_warning':'Author explicitly requires hyperopt; no saved optimized dict. This is intentionally a source-default diagnostic, not recovered intended optimized strategy.',
 'resource_policy':{'max_address_space_bytes':1024**3,'blas_threads':1,'minimum_free_disk_bytes':5*1024**3,'no_new_market_requests':True},'dependencies':dep}
 files=[p for p in ROOT.rglob('*') if p.is_file() and p.suffix in ['.py','.json'] and p.name!='protocol.json']
 spec['frozen_file_hashes']={str(p.relative_to(ROOT)):sha(p) for p in sorted(files)};write(ROOT/'specs/protocol.json',spec)
 print(json.dumps({'status':'C1_FROZEN_PENDING_INDEPENDENT_REVIEW','protocol_sha256':sha(ROOT/'specs/protocol.json'),'engine_sha256':sha(ROOT/'scripts/run_replay.py'),'frozen_at_utc':now,'returns_computed':False}))
if __name__=='__main__':main()
