#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Only project already-validated daily ledgers. Never include in public Git."""
import argparse,csv,json,pathlib,hashlib
R=pathlib.Path(__file__).resolve().parents[1]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rd(p):return json.loads(p.read_text())
def wr(p,x):
    with p.open('x') as f:json.dump(x,f,ensure_ascii=False,indent=2,allow_nan=False);f.write('\n')
p=argparse.ArgumentParser();p.add_argument('--work',required=True);p.add_argument('--output',required=True);a=p.parse_args();w=pathlib.Path(a.work);out=pathlib.Path(a.output);out.mkdir(exist_ok=False);spec=rd(R/'specs/protocol.json');s=rd(w/'summary.json');rec=rd(R/'artifacts/graph-record.json');assert rd(R/'artifacts/independent-real-result-audit.json')['status']=='PASS_INDEPENDENT_DECIMAL_ALL_CASE_EXECUTION_AND_METRICS';assert rd(R/'artifacts/local-recovery.json')['status']=='PASS_LOCAL_RECOVERY';curves={};sources={}
for name in ['base','buyhold']:
    full=list(csv.DictReader((w/f'{name}-nav.csv').open()));daily=list(csv.DictReader((w/f'{name}-daily-nav.csv').open()));peak=100000.;dd={}
    for row in full:peak=max(peak,float(row['equity']));dd[row['bar_index']]=float(row['equity'])/peak-1
    curves[name]=[{'date':row['date'],'timestamp_utc':row['timestamp_utc'],'equity':float(row['equity']),'drawdown':dd[row['bar_index']]} for row in daily];assert len(full)==4386 and len(daily)==731;assert abs(min(dd.values())+s['results'][name]['metrics']['max_drawdown'])<1e-12
    for suffix in ['nav','daily-nav']:
        f=w/f'{name}-{suffix}.csv';sources[f.name]={'bytes':f.stat().st_size,'sha256':sha(f)}
def met(name):
    m=dict(s['results'][name]['metrics']);m['max_drawdown']=-m['max_drawdown'];m['sharpe']=m['sharpe_daily'];m['start']='2023-01-01';m['end']='2024-12-31';return {'full':m}
d={'id':'M0316','run_id':spec['run_id'],'origin_run_id':spec['run_id'],'variant_id':spec['variant_id'],'family':spec['family'],'fidelity_class':'HYPOTHESIS','name':rec['name'],'fidelity_reason':'Source native signals and parameters; explicit limit quote/timeout/path/clock hypotheses; original runtime unknown.','spec':{'source_url':rd(R/'specs/source-manifest.json')['strategy_source']['url'],'params':spec,'assumptions':['signal-close GTC limit one-observation timeout; touch/fullfill assumed','O-L-H-C is synthetic path, not native nor conservative bound','ROI observed-open tier and conservative intrabar age-origin; native minute keys retained','Halt12 label effective14 proxy, no tick proof']},'audit':rec['audit'],'lineage':{**rec['related_results'][0],'input_sha256':s['input_sha256']},'limitations':['DIAGNOSTIC_ONLY/trusted=false; no PIT or strict finality proof','Exposed retrospective window, unknown prior search count, no OOS or promotion','Graph compatible projection does not imply import, binding or deployment'],'metrics':{'periods':met('base'),'same_instrument_benchmark':met('buyhold'),'additional_native_bar_lag':met('delay2'),'cost_sensitivity':{k:met(k) for k in ['fee0','fee20']}},'curve':curves['base'],'benchmark_curve':curves['buyhold'],'curve_meta':{'observations':4386,'total_observations':4386,'source_observations':4386,'returned_points':731,'rows':731,'benchmark_curve_available':True,'benchmark_returned_points':731,'sampling':'UTC last native4h close each day; no interpolation','frequency':'1d','initial_equity':100000,'initial_timestamp':spec['evaluation']['start'],'max_drawdown_sign':'negative','max_drawdown_source':'all4386 unsampled4h closes plus initial, not daily-projection recalculation','daily_drawdown_source':'daily close / running maximum of all4h closes plus initial -1','sharpe_frequency':'daily returns sqrt365 ddof1 rf0 includes initial equity','timestamp_convention':'close boundary;2025-01-01T00Z denotes2024-12-31 end','period_end_exclusive':spec['evaluation']['end_exclusive'],'source_hashes':sources},'data_attribution':rec['data_attribution'],'distribution':'PRIVATE_LIBRARY_ONLY_EXCLUDE_PUBLIC_GIT'}
wr(out/'graph-detail.private.json',d);wr(out/'private-manifest.json',{'id':'M0316','origin_run_id':spec['run_id'],'variant_id':spec['variant_id'],'fidelity_class':'HYPOTHESIS','protocol_sha256':sha(R/'specs/protocol.json'),'input_sha256':s['input_sha256'],'public_result_manifest_sha256':sha(R/'artifacts/result-manifest.json'),'source_ledgers':sources,'private_allowlist':{'graph-detail.private.json':{'bytes':(out/'graph-detail.private.json').stat().st_size,'sha256':sha(out/'graph-detail.private.json')}},'self_excluded':True,'public_upload':False,'new_returns_computed':False,'no_raw_candles_or_features':True});print('private731 daily projections verified, not imported')
