#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Freeze input/code/spec/exposure before invoking real-market replay.
Refuses overwrite. Never computes or examines market returns.
"""
import argparse,datetime,hashlib,json,pathlib,platform
ROOT=pathlib.Path(__file__).resolve().parents[1]
def digest(p):return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def dump(p,x):
    with pathlib.Path(p).open('x') as f:json.dump(x,f,ensure_ascii=False,indent=2);f.write('\n')
def freeze(input_path,input_manifest,data_qa):
    destination=ROOT/'specs/M0256-first-replay.json';exposure=ROOT/'specs/exposure.json'
    if destination.exists() or exposure.exists():raise FileExistsError('freeze already exists, do not overwrite')
    manifest=json.loads(pathlib.Path(input_manifest).read_text())
    assert manifest['timeframe']=='4h' and manifest['canonical_csv']['rows']==4572
    assert manifest['canonical_csv']['sha256']==digest(input_path)
    assert manifest['quality_status']=='DIAGNOSTIC_ONLY' and manifest['trusted'] is False
    assert manifest['row_quality']=='PASS' and manifest['reject_gap_policy_eligible'] is True
    assert all(manifest['integrity'][k]=='PASS' for k in ('official_checksums','zip_crc','utc_open_close_grid','all_native_fields_preserved'))
    assert manifest['builder_sha256']==digest(ROOT/'scripts/rebuild_official_bars.py')
    halt=json.loads((ROOT/'specs/market-halt-evidence.json').read_text())
    assert halt['status']=='PASS_BOUNDED_1H_TO_4H_MAPPING_NOT_TICK_PROOF' and halt['input_4h_sha256']==digest(input_path)
    qa=json.loads(pathlib.Path(data_qa).read_text());assert qa['status']=='PASS_RAW_TO_CANONICAL_INDEPENDENT_AUDIT' and qa['canonical_csv_sha256']==digest(input_path)
    source=json.loads((ROOT/'specs/source-manifest.json').read_text());now=datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z')
    spec={
      'record_id':'M0256','name':'AverageStrategy EMA8/EMA21','family':'PUBLIC-M0256-EMA-CROSS','run_id':'M0256-20261003-first-replay','variant_id':'M0256-BTCUSDT-4H-EMA8-21-LONG-20261003',
      'fidelity_class':'HYPOTHESIS','evidence_class':'retrospective_historical_replay','status':'explore / not promoted / not live-ready','frozen_at_utc':now,
      'source':{'repository':'freqtrade/freqtrade-strategies','commit':'f3340ce11f5bdf62f598522e64d1f5638eaa13f5','path':'user_data/strategies/berlinguyinca/AverageStrategy.py','author':'Gert Wohlgemuth','asset_selection':'BTCUSDT spot is predeclared researcher instance; author file does not specify a universe'},
      'framework_reference':{'name':'Freqtrade','version':'2025.9','commit':'c66e221012cd4d68cfdacf4735b38af33a487961','execution_engine_used':False,'purpose':'pinned qtpylib signal and documented engine comparison only; original runtime environment unknown'},
      'dependencies':{'numpy':'2.3.5','pandas':'2.2.3','TA-Lib':'0.6.8','ta_library':'0.6.4','python':'3.12.14','talib_compatibility':0,'ema_unstable_period':0},
      'parameters':{'ema_short':8,'ema_long':21,'hyperopt':False},
      'signals':{'indicator_price':'raw close','ema_seed':'first N raw closes arithmetic mean at index N-1, NaN before; then prev+(close-prev)*2/(N+1)','entry':'ema8[t]>ema21[t] and ema8[t-1]<=ema21[t-1] and volume[t]>0','exit':'ema21[t]>ema8[t] and ema21[t-1]<=ema8[t-1] and volume[t]>0','availability':'only after complete 4h candle close; NaN comparisons false; no warmup trading or warmup pending orders'},
      'risk':{'minimal_roi':{'0':0.5},'stoploss':-0.2,'trailing':False,'roi_threshold_formula':'entry_fill * (1+fee) * 1.5 / (1-fee)','roi_slippage':'threshold includes both fees but excludes sell slippage; target fill with 2bps adverse slip realizes 49.97% net trade return','stop_threshold_formula':'entry_fill * 0.8; fees and sell slippage add to nominal 20% price decline'},
      'execution':{'initial_cash':100000,'open_execution_overrides':{'1679659200000':{'effective_open_ms':1679666400000,'basis':'resume_1h_open_proxy','evidence':'specs/market-halt-evidence.json'}},'intrabar_execution_latest_overrides':{'1679644800000':1679657219999},'known_halt_handling':'2023-03-24 11:27–14:00 UTC. Nominal 12:00 4h open is modeled at 14:00 using matching 1h resumption open; not tick proof. No orders assigned inside known halt. No all-history downtime/PIT claim.','cash_currency':'USDT','cash_budget_fraction':0.95,'budget_includes_buy_fee':True,'fee_bps':8,'slippage_bps':2,'signal_delay_bars':1,'direction':'long_only','leverage':1,'max_positions':1,'pyramiding':False,'cash_interest':0,'funding':'not applicable, spot without borrowing','fill':'full fractional quantity; raw actual open for scheduled trades, threshold or raw open for risk exits; adverse slip each side','sequence':['due closed-bar exit signal at raw open','if flat due entry signal at raw open, never reenter after exit in same bar','existing/new position opening gap: stop if open<=stop, else ROI if open>=ROI','otherwise within-bar low stop check before high ROI check','mark remaining quantity at raw raw close; generate no warmup orders'],'ambiguity':'When open is between thresholds and both low/high touch risk levels, stop first; unknown 4h intrabar path, no subbar replay','gap':'scheduled exit still has open priority; risk gap fills at raw open plus adverse sell slip; gap crossing ROI is evaluated before subsequent intrabar low','terminal':'no forced liquidation; open position marked at final raw close, unpaid hypothetical exit costs not deducted','pending':'signal from evaluation-close only; arrives after configured number of bars; stale buy while long or exit while flat ignored; no execution beyond evaluation end','limits':'historical lot/min-notional limits, book liquidity, queueing, partial fills, funding and borrow not modeled'},
      'input':{'filename':pathlib.Path(input_path).name,'sha256':digest(input_path),'bytes':pathlib.Path(input_path).stat().st_size,'start':'2022-12-01T00:00:00Z','end_exclusive':'2025-01-01T00:00:00Z','expected_rows':4572,'exchange':'binance','market_type':'spot','symbol':'BTCUSDT','timeframe':'4h','source':'official Binance Vision monthly archives','data_profile':'NATIVE12_CANONICAL_DIAGNOSTIC_V1, explicit spot handoff; not canonical perpetual research bundle','quality_status':'DIAGNOSTIC_ONLY','trusted':False,'strict_core_finality':'NOT_ESTABLISHED','provider_clock_newer_current_bucket':'UNAVAILABLE_HTTP451_no_bypass','raw_manifest_sha256':digest(input_manifest),'data_qa_sha256':digest(data_qa),'pit_status':'not proven: current retrospective archives, no contemporaneous snapshots or author universe'},
      'evaluation':{'start':'2023-01-01T00:00:00Z','end_exclusive':'2025-01-01T00:00:00Z','expected_rows':4386,'initial_state':'all cash, no warmup signal carried to first evaluation open; first strategy entry possible at second evaluation open'},
      'metrics':{'sharpe':'UTC end-of-day equity returns including initial equity, sample standard deviation ddof=1, sqrt(365), risk-free zero','sharpe_4h':'additional bar-close returns sqrt(365*6), ddof=1','max_drawdown':'maximum decline from running peak over initial capital plus all unsampled 4h bar-close equities; no intrabar equity drawdown claim','annualized_return':'(end/start equity)^(365/731)-1','daily_curve':'last 4h close of each UTC date; timestamp is close boundary, e.g. 2025-01-01T00Z represents 2024-12-31 end-of-day','position_bar_fraction':'fraction of evaluated bar-close states with quantity>0, not elapsed-time exact exposure'},
      'cases':[{'name':'base','fee_bps':8,'delay_bars':1},{'name':'fee0','fee_bps':0,'delay_bars':1},{'name':'fee20','fee_bps':20,'delay_bars':1},{'name':'delay2','fee_bps':8,'delay_bars':2},{'name':'buyhold','fee_bps':8,'delay_bars':1,'buy_hold':True}],
      'buyhold':'95% inclusive cash budget at first evaluation raw open, same fees/slip and terminal mark, no ROI/stop/exit signal',
      'exposure':{'window_previously_exposed':True,'historical_total_search_count':'UNKNOWN','oos_claim':False,'DSR_or_PBO_claim':False,'strategy_ids':1,'strategy_configurations':4,'controls':1,'parameter_searches':0,'source_of_assignment':'a7b7ea4c09863306ed41427c19af072c0db20139 dot-batch001 handoff'},
      'supporting_evidence_hashes':{str(p.relative_to(ROOT)):digest(p) for p in sorted((ROOT/'specs').glob('*')) if p.is_file() and p.name not in ('M0256-first-replay.json','exposure.json')},
      'source_hashes':{'sources/'+x['filename']:x['sha256'] for x in source['files']},'code_hashes':{str(p.relative_to(ROOT)):digest(p) for p in sorted((ROOT/'scripts').glob('*.py'))}}
    dump(destination,spec)
    dump(exposure,{'record_id':'M0256','recorded_before_returns_at_utc':now,'protocol_sha256':digest(destination),'source_manifest_sha256':digest(ROOT/'specs/source-manifest.json'),'input_sha256':spec['input']['sha256'],'code_hashes':spec['code_hashes'],'first_execution_attempt':1,'strategy_ids':1,'predeclared_strategy_configurations':4,'predeclared_controls':1,'hyperopt':False,'historical_window_already_exposed':True,'prior_catalog_search_count':'UNKNOWN','pure_oos':False,'actual_model':'UNKNOWN','actual_reasoning_effort':'UNKNOWN','note':'QA/rebuild repeats are replay attempts, not new strategy IDs; preserve failed outputs and revisions if any; no model/effort backfill'})
    return {'spec_sha256':digest(destination),'exposure_sha256':digest(exposure),'frozen_at_utc':now}
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--input',required=True);p.add_argument('--input-manifest',required=True);p.add_argument('--data-qa',required=True);a=p.parse_args();print(json.dumps(freeze(a.input,a.input_manifest,a.data_qa),indent=2))
